# Generated by Django 3.2.7 on 2021-10-08 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptkeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_price_of_asset', models.DecimalField(decimal_places=8, max_digits=19)),
                ('datetime_of_transaction', models.DateTimeField()),
                ('quantity_of_transaction', models.DecimalField(decimal_places=8, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_price_of_asset', models.DecimalField(decimal_places=8, max_digits=19)),
                ('datetime_of_transaction', models.DateTimeField()),
                ('quantity_of_transaction', models.DecimalField(decimal_places=8, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
