# Generated by Django 3.2.7 on 2021-10-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0004_alter_transaction_usd_price_of_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='datetime_of_transaction',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity_of_transaction',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='usd_price_of_asset',
            new_name='usd_price',
        ),
    ]
