# Generated by Django 3.2.7 on 2021-10-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0005_auto_20211008_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_to',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
