# Generated by Django 3.2.7 on 2021-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0006_auto_20211015_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Interest', 'Interest')], max_length=40),
        ),
    ]
