# Generated by Django 3.2.7 on 2021-10-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0009_alter_transaction_usd_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
