# Generated by Django 3.2.7 on 2021-10-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0010_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
