# Generated by Django 3.2.7 on 2021-10-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0011_transaction_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='note',
            new_name='notes',
        ),
    ]
