# Generated by Django 3.2.7 on 2021-10-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0012_rename_note_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
