# Generated by Django 3.2.7 on 2021-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0013_auto_20211028_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Interest', 'Interest'), ('Send', 'Send'), ('Airdrop', 'Airdrop')], max_length=40),
        ),
    ]
