# Generated by Django 3.2.7 on 2021-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0014_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='usd_total_no_fees',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='usd_total_with_fees',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
