# Generated by Django 3.2.7 on 2021-11-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0015_auto_20211113_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='usd_price',
            new_name='spot_price',
        ),
    ]
