# Generated by Django 3.2.7 on 2021-11-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0019_auto_20211122_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='spot_price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_fee',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_total_no_fees',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_total_with_fees',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
