# Generated by Django 3.2.7 on 2021-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0020_auto_20211123_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='usd_total_no_fees',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_total_with_fees',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
