# Generated by Django 3.2.7 on 2021-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0021_auto_20211126_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='usd_fee',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
