# Generated by Django 3.2.7 on 2021-12-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptkeeper', '0022_alter_transaction_usd_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='needs_reviewed',
            field=models.BooleanField(null=True),
        ),
    ]
